### ISSUE TITLE
.tern-config runtime error

### ISSUE THREAD

**Issue by ain** [ain/.vim#46]
When opening a JS file, the following error is thrown:
```
RuntimeError: Warning: Unable to detect a .tern-project file in the hierarchy before /Users/ain/projects/iptools-jquery-modal and no global .tern-config file was found. This is required for accurate JavaScript completion. Please see the User Guide for details. 
```

**Comment by pygo** [comment]
I am getting this too.

**Comment by pygo** [comment]
Try re-compile YouCOmpleteMe
####
cd ~/.vim/bundle/YouCompleteMe/
./install.py --tern-completer

**Comment by ain** [comment]
@pygo thanks for the heads up. This problem seems to be resolved. 

The `--tern-completer` option [was already there though](https://github.com/ain/.vim/blob/master/update#L13).

**Comment by andythedandyone** [comment]
I'm still getting this error, above solutions didn't work.
kunbuntu 16.04

**Comment by andythedandyone** [comment]
here is the solution that worked for me.
Apparently, it is not getting created automatically.
So, create the file manually.
touch ~/.tern-project
then place this
```
{
  "plugins": {
    "node": {},
    "es_modules": {}
  },
  "libs": [
    "ecma5",
    "ecma6"
  ],
  "ecmaVersion": 6
}
```
or this 
```
 {
   "libs": [
     "browser",
     "react"
   ],
   "plugins": {
       "doc_comment": null,
       "angular": {},
       "node": {}
   }
 }
```

**Comment by ain** [comment]
Thanks for coming back with your feedback @andythedandyone!

**Comment by dmgolembiowski** [comment]
Alternatively, if you're getting this error on other Debian-based OS's like @codercodingthecode but `~/.tern-project` does not work for you, you might need to change the filename to `.tern-config` and then it should work as expected

**Comment by ciurca** [comment]
> here is the solution that worked for me.
> Apparently, it is not getting created automatically.
> So, create the file manually.
> touch ~/.tern-project
> then place this
> 
> ```
> {
>   "plugins": {
>     "node": {},
>     "es_modules": {}
>   },
>   "libs": [
>     "ecma5",
>     "ecma6"
>   ],
>   "ecmaVersion": 6
> }
> ```
> 
> or this
> 
> ```
>  {
>    "libs": [
>      "browser",
>      "react"
>    ],
>    "plugins": {
>        "doc_comment": null,
>        "angular": {},
>        "node": {}
>    }
>  }
> ```
This fixed my problem on Ubuntu 20.04.

**Comment by harryghgim** [comment]
For those who are experiencing similar issue in Oct, 2020, ycm official doc recommends to delete [Tern server directory](https://github.com/ycm-core/YouCompleteMe#javascript-and-typescript-semantic-completion), due to its not well maintainability. 

> ... you are encouraged to do the switch by deleting the third_party/ycmd/third_party/tern_runtime/node_modules directory in YCM folder

So I deleted the directory and `:YcmRestartServer`, and it works perfectly.

**Comment by iamshm** [comment]
> here is the solution that worked for me.
> Apparently, it is not getting created automatically.
> So, create the file manually.
> touch ~/.tern-project
> then place this
> 
> ```
> {
>   "plugins": {
>     "node": {},
>     "es_modules": {}
>   },
>   "libs": [
>     "ecma5",
>     "ecma6"
>   ],
>   "ecmaVersion": 6
> }
> ```
> 
> or this
> 
> ```
>  {
>    "libs": [
>      "browser",
>      "react"
>    ],
>    "plugins": {
>        "doc_comment": null,
>        "angular": {},
>        "node": {}
>    }
>  }
> ```

In what location this file to be created

**Comment by iamshm** [comment]
> For those who are experiencing similar issue in Oct, 2020, ycm official doc recommends to delete [Tern server directory](https://github.com/ycm-core/YouCompleteMe#javascript-and-typescript-semantic-completion), due to its not well maintainability.
> 
> > ... you are encouraged to do the switch by deleting the third_party/ycmd/third_party/tern_runtime/node_modules directory in YCM folder
> 
> So I deleted the directory and `:YcmRestartServer`, and it works perfectly.

This is the solution 🔥

**Comment by LeoCaprile** [comment]
> For those who are experiencing similar issue in Oct, 2020, ycm official doc recommends to delete [Tern server directory](https://github.com/ycm-core/YouCompleteMe#javascript-and-typescript-semantic-completion), due to its not well maintainability.
> 
> > ... you are encouraged to do the switch by deleting the third_party/ycmd/third_party/tern_runtime/node_modules directory in YCM folder
> 
> So I deleted the directory and `:YcmRestartServer`, and it works perfectly.

THIS WORKS!!

**Comment by Havanero** [comment]
> here is the solution that worked for me. Apparently, it is not getting created automatically. So, create the file manually. touch ~/.tern-project then place this
> 
> ```
> {
>   "plugins": {
>     "node": {},
>     "es_modules": {}
>   },
>   "libs": [
>     "ecma5",
>     "ecma6"
>   ],
>   "ecmaVersion": 6
> }
> ```
> 
> or this
> 
> ```
>  {
>    "libs": [
>      "browser",
>      "react"
>    ],
>    "plugins": {
>        "doc_comment": null,
>        "angular": {},
>        "node": {}
>    }
>  }
> ```

worked for me
`└─ $ ▶ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic
`
